### ISSUE TITLE
File Handling for Non-English Alphabets

### ISSUE THREAD

**Issue by elbre** [digital-preservation/droid#1029]
Hello,

I would like to bring attention to an issue I encountered while working with Droid, specifically when dealing with files containing characters from alphabets other than English.

Initially, we suspected that the problem might be related to using *.zip files. However, after further investigation, we observed similar issues when generating *.7z files and attempting different export methods.

To assist in resolving this matter, I am attaching the original files, the export, and a screenshot of the application to provide a comprehensive overview.

I am curious to know if there are plans to address these issues in the near future or if there is already a known solution?

![czechfilesfail](https://github.com/digital-preservation/droid/assets/48675042/7eb8e676-625b-4384-91f4-876fb8be9e58)

[aaa.txt](https://github.com/digital-preservation/droid/files/13544203/aaa.txt)
[Jindřich Šťovíček.zip](https://github.com/digital-preservation/droid/files/13544205/Jindrich.Stovicek.zip)

**Comment by sparkhi** [comment]
Hi @elbre 
Thanks for raising the issue and attaching the supporting documents. 
Unfortunately, there is no already known solution for it as of now. I'll investigate further and update.  

Regards,

**Comment by ross-spencer** [comment]
Just to note, a workaround might be to unzip the contents here:

![image](https://github.com/digital-preservation/droid/assets/1880412/ff661602-8505-4a19-8b2a-7aa47d09ea72)

Which might point to there being something in the archive handling process in general causing the issue. I'm not sure. It's actually the same pattern in Siegfried too cc. @richardlehane.

e.g. 

Without extracting:

```yaml
---
filename : 'Jindrich.Stovicek.zip#Jind²ich µ£ovíƒek/ⁿíƒansk∞ k²iτ£ál/ⁿí'
filesize : 0
modified : 2023-11-29T21:59:26Z
errors   : 'empty source'
matches  :
  - ns      : 'pronom'
    id      : 'UNKNOWN'
    format  : 
    version : 
    mime    : 
    class   : 
    basis   : 
    warning : 'no match'
---
filename : 'Jindrich.Stovicek.zip#Jind²ich µ£ovíƒek/µt╪σátko/µ'
filesize : 0
modified : 2023-11-29T22:00:50Z
errors   : 'empty source'
matches  :
  - ns      : 'pronom'
    id      : 'UNKNOWN'
    format  : 
    version : 
    mime    : 
    class   : 
    basis   : 
    warning : 'no match'
```

With extracting:

```yaml
---
filename : 'Říčanský křišťál/Říčanský křišťál.txt'
filesize : 0
modified : 2023-11-29T21:59:26+01:00
errors   : 'empty source'
matches  :
  - ns      : 'pronom'
    id      : 'x-fmt/111'
    format  : 'Plain Text File'
    version : 
    mime    : 'text/plain'
    class   : 
    basis   : 'extension match txt'
    warning : 'match on extension only'
---
filename : 'Štěňátko/Štěňátko.txt'
filesize : 0
modified : 2023-11-29T22:00:50+01:00
errors   : 'empty source'
matches  :
  - ns      : 'pronom'
    id      : 'x-fmt/111'
    format  : 'Plain Text File'
    version : 
    mime    : 'text/plain'
    class   : 
    basis   : 'extension match txt'
    warning : 'match on extension only'
```

Was just interested to take a look at this as we had problems with earlier DROID releases with the Māori language character set, but I had  thought they were resolved. I guess we didn't process a lot of zips back in the day!
